# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package.json
COPY package.json ./

# Install dependencies
RUN npm install --production --ignore-scripts

# Copy the built files (dist) into the image
COPY dist/ ./dist/

# Ensure the entrypoint is executable
RUN chmod +x dist/*.js

# Start the server using the built entrypoint (using stdio transport)
CMD [ "node", "dist/index.js" ]
